<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\QuanLySinhVien\Models\*.cs" Link="Models\%(Filename)%(Extension)" />
    <Compile Include="..\QuanLySinhVien\DAO\*.cs" Link="DAO\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
